# Generated by Django 5.1 on 2026-07-31 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("professionalism", models.CharField(blank=True, max_length=200)),
                ("phonenumber", models.CharField(blank=True, max_length=30)),
                ("details", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("birth_date", models.CharField(blank=True, max_length=20)),
                ("height", models.CharField(blank=True, max_length=20)),
                ("weight", models.CharField(blank=True, max_length=20)),
                ("blood_type", models.CharField(blank=True, max_length=10)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("insurance", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=200)),
                ("emergency_name", models.CharField(blank=True, max_length=200)),
                ("emergency_phone", models.CharField(blank=True, max_length=30)),
                ("current_illnesses", models.TextField(blank=True)),
                ("first_period_age", models.CharField(blank=True, max_length=10)),
                ("cycle_duration", models.CharField(blank=True, max_length=20)),
                ("bleeding_duration", models.CharField(blank=True, max_length=20)),
                ("pain_level", models.CharField(blank=True, max_length=100)),
                ("menstrual_symptoms", models.JSONField(blank=True, default=list)),
                ("pregnancy_count", models.CharField(blank=True, max_length=10)),
                ("pregnancy_symptoms", models.JSONField(blank=True, default=list)),
                ("menopause_symptoms", models.JSONField(blank=True, default=list)),
                ("medications", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cirugia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("date", models.CharField(blank=True, max_length=20)),
                (
                    "medical_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cirugias",
                        to="api.medicalinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenopauseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("exercise", models.BooleanField(default=False)),
                ("vitamins", models.BooleanField(default=False)),
                ("symptoms", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menopause_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="PregnancyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("baby_movement", models.BooleanField(default=False)),
                ("doctor_appointment", models.BooleanField(default=False)),
                ("symptoms", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancy_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("reminder_offset", models.CharField(blank=True, max_length=20)),
                ("notification_id", models.CharField(blank=True, max_length=100)),
                (
                    "pregnancy_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="api.pregnancyentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("photo_uri", models.TextField(blank=True)),
                (
                    "health_stage",
                    models.CharField(
                        choices=[
                            ("menstruacion", "Menstruación"),
                            ("embarazo", "Embarazo"),
                            ("menopausia", "Menopausia"),
                        ],
                        default="menstruacion",
                        max_length=20,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("guest", "Guest"), ("registered", "Registered")],
                        default="guest",
                        max_length=20,
                    ),
                ),
                ("onboarding_complete", models.BooleanField(default=False)),
                (
                    "pregnancy_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cycle_reset_date", models.DateField(blank=True, null=True)),
                (
                    "app_language",
                    models.CharField(
                        choices=[("es", "Español"), ("mis", "Miskito")],
                        default="es",
                        max_length=10,
                    ),
                ),
                (
                    "audio_language",
                    models.CharField(
                        choices=[("es", "Español"), ("none", "None")],
                        default="es",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("reminder_offset", models.CharField(blank=True, max_length=20)),
                ("notification_id", models.CharField(blank=True, max_length=100)),
                (
                    "menopause_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplements",
                        to="api.menopauseentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("text", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="MenstruationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("period", models.BooleanField(default=False)),
                ("exercise", models.BooleanField(default=False)),
                ("mood", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menstruation_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("emoji", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="MythAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("answered_true", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myth_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
