# Generated by Django 5.1 on 2026-08-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menopauseentry",
            name="vitamins",
        ),
    ]
