# Generated by Django 5.1 on 2026-10-09 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_menopauseentry_vitamins"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40)),
                (
                    "apk",
                    models.FileField(
                        upload_to="app-releases/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["apk"])
                        ],
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "app release",
                "verbose_name_plural": "app releases",
                "ordering": ("-uploaded_at", "-pk"),
            },
        ),
    ]
